ci: pre-commit hook sample for MSRV

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -4,11 +4,22 @@
 script=$(basename "$0")
 
 fail() {
-	echo "$script: pre-commit hook failed" >&2
+	echo "$script: pre-commit hook failed: $1" >&2
 	exit 1
 }
 
-cargo fmt --check && \
+MSRV="1.60"
+
+cargo fmt --check || fail "cargo fmt --check"
+
+cargo +$MSRV clippy --no-deps --no-default-features -- -Dwarnings && \
+cargo +$MSRV clippy --no-deps --no-default-features --features log -- -Dwarnings && \
+cargo +$MSRV clippy --no-deps --no-default-features --features log,ssl -- -Dwarnings && \
+cargo +$MSRV clippy --no-deps --no-default-features --features log,ssl-native-tls -- -Dwarnings && \
+cargo +$MSRV clippy --no-deps --no-default-features --features ssl -- -Dwarnings && \
+cargo +$MSRV clippy --no-deps --no-default-features --features ssl-native-tls -- -Dwarnings || \
+fail "cargo +$MSRV clippy"
+
 cargo clippy --no-deps --no-default-features -- -Dwarnings && \
 cargo clippy --no-deps --no-default-features --features ssl -- -Dwarnings && \
 cargo clippy --no-deps --no-default-features --features ssl-native-tls -- -Dwarnings && \
@@ -17,5 +28,5 @@ cargo clippy --no-deps --no-default-features --features log -- -Dwarnings && \
 cargo clippy --no-deps --no-default-features --features socket2 -- -Dwarnings && \
 cargo clippy --no-deps --features ssl -- -Dwarnings && \
 cargo clippy --no-deps --features ssl-native-tls -- -Dwarnings && \
-cargo clippy --no-deps --features ssl-rustls -- -Dwarnings || fail
-
+cargo clippy --no-deps --features ssl-rustls -- -Dwarnings || \
+fail "cargo clippy"
